/**
 * Rick and Morty API
 * Access information about characters from Rick and Morty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Character from './model/Character';
import CharacterListResponse from './model/CharacterListResponse';
import CharacterListResponseInfo from './model/CharacterListResponseInfo';
import CharacterLocation from './model/CharacterLocation';
import CharacterOrigin from './model/CharacterOrigin';
import DefaultApi from './api/DefaultApi';


/**
* Access information about characters from Rick and Morty..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RickAndMortyApi = require('index'); // See note below*.
* var xxxSvc = new RickAndMortyApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RickAndMortyApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RickAndMortyApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RickAndMortyApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Character model constructor.
     * @property {module:model/Character}
     */
    Character,

    /**
     * The CharacterListResponse model constructor.
     * @property {module:model/CharacterListResponse}
     */
    CharacterListResponse,

    /**
     * The CharacterListResponseInfo model constructor.
     * @property {module:model/CharacterListResponseInfo}
     */
    CharacterListResponseInfo,

    /**
     * The CharacterLocation model constructor.
     * @property {module:model/CharacterLocation}
     */
    CharacterLocation,

    /**
     * The CharacterOrigin model constructor.
     * @property {module:model/CharacterOrigin}
     */
    CharacterOrigin,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
