/**
 * Rick and Morty API
 * Access information about characters from Rick and Morty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CharacterListResponseInfo model module.
 * @module model/CharacterListResponseInfo
 * @version 1.0.0
 */
class CharacterListResponseInfo {
    /**
     * Constructs a new <code>CharacterListResponseInfo</code>.
     * @alias module:model/CharacterListResponseInfo
     */
    constructor() { 
        
        CharacterListResponseInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CharacterListResponseInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CharacterListResponseInfo} obj Optional instance to populate.
     * @return {module:model/CharacterListResponseInfo} The populated <code>CharacterListResponseInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CharacterListResponseInfo();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('pages')) {
                obj['pages'] = ApiClient.convertToType(data['pages'], 'Number');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('prev')) {
                obj['prev'] = ApiClient.convertToType(data['prev'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CharacterListResponseInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CharacterListResponseInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['next'] && !(typeof data['next'] === 'string' || data['next'] instanceof String)) {
            throw new Error("Expected the field `next` to be a primitive type in the JSON string but got " + data['next']);
        }
        // ensure the json data is a string
        if (data['prev'] && !(typeof data['prev'] === 'string' || data['prev'] instanceof String)) {
            throw new Error("Expected the field `prev` to be a primitive type in the JSON string but got " + data['prev']);
        }

        return true;
    }


}



/**
 * The total number of characters.
 * @member {Number} count
 */
CharacterListResponseInfo.prototype['count'] = undefined;

/**
 * The total number of pages.
 * @member {Number} pages
 */
CharacterListResponseInfo.prototype['pages'] = undefined;

/**
 * URL of the next page.
 * @member {String} next
 */
CharacterListResponseInfo.prototype['next'] = undefined;

/**
 * URL of the previous page.
 * @member {String} prev
 */
CharacterListResponseInfo.prototype['prev'] = undefined;






export default CharacterListResponseInfo;

